component_depth: 3
languages:
- javascript
exclude:
- /dist/.*
- /node_modules/.*
- .*/systemjs.config\.js
- /styles/.*
- .*/gulpfile\.js
- .*/karma.conf\.js
- /build/.*
- .*/serviceProxyServer\.js
- /src/app/services/tweets\.js