module.exports = [
    {
        "trends":[
            {
                "name":"#NBAFinals",
                "url":"http:\/\/twitter.com\/search?q=%23NBAFinals",
                "promoted_content":null,
                "query":"%23NBAFinals",
                "tweet_volume":349651
            },
            {
                "name":"Juan Jos\u00E9 Paredes",
                "url":"http:\/\/twitter.com\/search?q=%22Juan+Jos%C3%A9+Paredes%22",
                "promoted_content":null,
                "query":"%22Juan+Jos%C3%A9+Paredes%22",
                "tweet_volume":null
            },
            {
                "name":"Volcano",
                "url":"http:\/\/twitter.com\/search?q=M%C3%A9xico",
                "promoted_content":null,
                "query":"M%C3%A9xico",
                "tweet_volume":333654
            },
            {
                "name":"Petapa",
                "url":"http:\/\/twitter.com\/search?q=Petapa",
                "promoted_content":null,
                "query":"Petapa",
                "tweet_volume":null
            },
            {
                "name":"Anthony Bourdain",
                "url":"http:\/\/twitter.com\/search?q=%22Anthony+Bourdain%22",
                "promoted_content":null,
                "query":"%22Anthony+Bourdain%22",
                "tweet_volume":1818194
            },
            {
                "name":"Carlos Soto",
                "url":"http:\/\/twitter.com\/search?q=%22Carlos+Soto%22",
                "promoted_content":null,
                "query":"%22Carlos+Soto%22",
                "tweet_volume":null
            },
            {
                "name":"Sagrado Coraz\u00F3n de Jes\u00FAs",
                "url":"http:\/\/twitter.com\/search?q=%22Sagrado+Coraz%C3%B3n+de+Jes%C3%BAs%22",
                "promoted_content":null,
                "query":"%22Sagrado+Coraz%C3%B3n+de+Jes%C3%BAs%22",
                "tweet_volume":13226
            },
            {
                "name":"#ElTri",
                "url":"http:\/\/twitter.com\/search?q=%23ElTri",
                "promoted_content":null,
                "query":"%23ElTri",
                "tweet_volume":null
            },
            {
                "name":"#NACIONALES",
                "url":"http:\/\/twitter.com\/search?q=%23NACIONALES",
                "promoted_content":null,
                "query":"%23NACIONALES",
                "tweet_volume":null
            },
            {
                "name":"#InfraestructuraGT",
                "url":"http:\/\/twitter.com\/search?q=%23InfraestructuraGT",
                "promoted_content":null,
                "query":"%23InfraestructuraGT",
                "tweet_volume":null
            },
            {
                "name":"Francia",
                "url":"http:\/\/twitter.com\/search?q=Francia",
                "promoted_content":null,
                "query":"Francia",
                "tweet_volume":31312
            },
            {
                "name":"#AvanceEU",
                "url":"http:\/\/twitter.com\/search?q=%23AvanceEU",
                "promoted_content":null,
                "query":"%23AvanceEU",
                "tweet_volume":null
            },
            {
                "name":"Preventivo",
                "url":"http:\/\/twitter.com\/search?q=Preventivo",
                "promoted_content":null,
                "query":"Preventivo",
                "tweet_volume":null
            },
            {
                "name":"Los Juanquis",
                "url":"http:\/\/twitter.com\/search?q=%22Los+Juanquis%22",
                "promoted_content":null,
                "query":"%22Los+Juanquis%22",
                "tweet_volume":null
            },
            {
                "name":"EN VIVO",
                "url":"http:\/\/twitter.com\/search?q=%22EN+VIVO%22",
                "promoted_content":null,
                "query":"%22EN+VIVO%22",
                "tweet_volume":47227
            },
            {
                "name":"USAC",
                "url":"http:\/\/twitter.com\/search?q=USAC",
                "promoted_content":null,
                "query":"USAC",
                "tweet_volume":null
            },
            {
                "name":"Neto Bran",
                "url":"http:\/\/twitter.com\/search?q=%22Neto+Bran%22",
                "promoted_content":null,
                "query":"%22Neto+Bran%22",
                "tweet_volume":null
            },
            {
                "name":"Eduardo Casta\u00F1eda",
                "url":"http:\/\/twitter.com\/search?q=%22Eduardo+Casta%C3%B1eda%22",
                "promoted_content":null,
                "query":"%22Eduardo+Casta%C3%B1eda%22",
                "tweet_volume":null
            },
            {
                "name":"Israel",
                "url":"http:\/\/twitter.com\/search?q=Israel",
                "promoted_content":null,
                "query":"Israel",
                "tweet_volume":189864
            },
            {
                "name":"Santiaguito",
                "url":"http:\/\/twitter.com\/search?q=Santiaguito",
                "promoted_content":null,
                "query":"Santiaguito",
                "tweet_volume":null
            },
            {
                "name":"Sandra Jovel",
                "url":"http:\/\/twitter.com\/search?q=%22Sandra+Jovel%22",
                "promoted_content":null,
                "query":"%22Sandra+Jovel%22",
                "tweet_volume":null
            },
            {
                "name":"Donald Trump",
                "url":"http:\/\/twitter.com\/search?q=%22Donald+Trump%22",
                "promoted_content":null,
                "query":"%22Donald+Trump%22",
                "tweet_volume":269114
            },
            {
                "name":"Pac\u00EDfico",
                "url":"http:\/\/twitter.com\/search?q=Pac%C3%ADfico",
                "promoted_content":null,
                "query":"Pac%C3%ADfico",
                "tweet_volume":14609
            },
            {
                "name":"El Salvador",
                "url":"http:\/\/twitter.com\/search?q=%22El+Salvador%22",
                "promoted_content":null,
                "query":"%22El+Salvador%22",
                "tweet_volume":null
            },
            {
                "name":"Insivumeh",
                "url":"http:\/\/twitter.com\/search?q=Insivumeh",
                "promoted_content":null,
                "query":"Insivumeh",
                "tweet_volume":null
            },
            {
                "name":"San Juan Ostuncalco",
                "url":"http:\/\/twitter.com\/search?q=%22San+Juan+Ostuncalco%22",
                "promoted_content":null,
                "query":"%22San+Juan+Ostuncalco%22",
                "tweet_volume":null
            },
            {
                "name":"San Juan Alotenango",
                "url":"http:\/\/twitter.com\/search?q=%22San+Juan+Alotenango%22",
                "promoted_content":null,
                "query":"%22San+Juan+Alotenango%22",
                "tweet_volume":null
            },
            {
                "name":"Suchitep\u00E9quez",
                "url":"http:\/\/twitter.com\/search?q=Suchitep%C3%A9quez",
                "promoted_content":null,
                "query":"Suchitep%C3%A9quez",
                "tweet_volume":null
            },
            {
                "name":"BOLET\u00CDN INFORMATIVO",
                "url":"http:\/\/twitter.com\/search?q=%22BOLET%C3%8DN+INFORMATIVO%22",
                "promoted_content":null,
                "query":"%22BOLET%C3%8DN+INFORMATIVO%22",
                "tweet_volume":null
            },
            {
                "name":"Jehov\u00E1",
                "url":"http:\/\/twitter.com\/search?q=Jehov%C3%A1",
                "promoted_content":null,
                "query":"Jehov%C3%A1",
                "tweet_volume":null
            },
            {
                "name":"#CompromisosVsTrata",
                "url":"http:\/\/twitter.com\/search?q=%23CompromisosVsTrata",
                "promoted_content":null,
                "query":"%23CompromisosVsTrata",
                "tweet_volume":null
            },
            {
                "name":"#FuerzaGuate",
                "url":"http:\/\/twitter.com\/search?q=%23FuerzaGuate",
                "promoted_content":null,
                "query":"%23FuerzaGuate",
                "tweet_volume":null
            },
            {
                "name":"#RenunciaYaJimmyMorales",
                "url":"http:\/\/twitter.com\/search?q=%23RenunciaYaJimmyMorales",
                "promoted_content":null,
                "query":"%23RenunciaYaJimmyMorales",
                "tweet_volume":null
            },
            {
                "name":"#AlcaldiasAuxiliaresTrabajando",
                "url":"http:\/\/twitter.com\/search?q=%23AlcaldiasAuxiliaresTrabajando",
                "promoted_content":null,
                "query":"%23AlcaldiasAuxiliaresTrabajando",
                "tweet_volume":null
            },
            {
                "name":"#NoM\u00E1sViolencia",
                "url":"http:\/\/twitter.com\/search?q=%23NoM%C3%A1sViolencia",
                "promoted_content":null,
                "query":"%23NoM%C3%A1sViolencia",
                "tweet_volume":null
            },
            {
                "name":"#Nicaragua",
                "url":"http:\/\/twitter.com\/search?q=%23Nicaragua",
                "promoted_content":null,
                "query":"%23Nicaragua",
                "tweet_volume":21335
            },
            {
                "name":"#NoSeanMulasMuch\u00E1",
                "url":"http:\/\/twitter.com\/search?q=%23NoSeanMulasMuch%C3%A1",
                "promoted_content":null,
                "query":"%23NoSeanMulasMuch%C3%A1",
                "tweet_volume":null
            },
            {
                "name":"#RolandGarros",
                "url":"http:\/\/twitter.com\/search?q=%23RolandGarros",
                "promoted_content":null,
                "query":"%23RolandGarros",
                "tweet_volume":21435
            },
            {
                "name":"#INAB",
                "url":"http:\/\/twitter.com\/search?q=%23INAB",
                "promoted_content":null,
                "query":"%23INAB",
                "tweet_volume":null
            }
        ],
        "as_of":"2018-06-09T07:38:11Z",
        "created_at":"2018-06-09T07:32:11Z",
        "locations":[
            {
                "name":"Guatemala",
                "woeid":23424834
            }
        ]
    }
];